name: OpenCoreCompile

on:
  push:
    branches: master
  schedule:
    - cron: '* 8 */1 * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1
jobs:
  OpenCoreCompile:
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
    - uses: actions/checkout@v3

    - name: Add Linux Toolchain
      run: brew tap FiloSottile/homebrew-musl-cross

    - name: Install Linux Toolchain
      run: brew install musl-cross
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Install Dependencies
      run: brew install openssl mingw-w64
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
        HOMEBREW_NO_AUTO_UPDATE: 1
    - name: Build OpenCore
      run: |
        git clone https://github.com/acidanthera/OpenCorePkg.git
        cd OpenCorePkg
        git clone https://github.com/acidanthera/ocbuild.git
        cd ocbuild && chmod +x ci-bootstrap.sh && ./ci-bootstrap.sh && cd ..
        ./build_duet.tool
        ./build_oc.tool
        ls
    - name: Generate Prerelease Release Notes
      run: |
        echo '### 免責聲明：' >> ReleaseNotes.md
        echo '***自动编译开发版OpenCore***' >> ReleaseNotes.md
        echo '它尚未准备好供日常使用，我们不保证其可用性。' >> ReleaseNotes.md
    - name: Delete Old Prerelease
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        tag_name: OpenCore
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish GitHub Release
      if: contains(github.event.head_commit.message, 'Bump version') == false
      uses: ncipollo/release-action@v1.8.6
      with:
        #prerelease: true
        bodyFile: ReleaseNotes.md
        artifacts: "OpenCorePkg/Binaries/*.zip"
        tag: "OpenCore"
        token: ${{ secrets.GITHUB_TOKEN }}
